### PR TITLE
Embed rustproto.proto and WKT protos in protobuf-codegen-pure

### LINKED ISSUE #312: Support well known types in protobuf-codegen-pure
As far as I can tell "well known types" do not work with `protobuf-codegen-pure` because the types are not translated to the generated protobuf lib well known type.I assume the fn `type_name_to_rust_relative` from `protobuf-codgen/src/rust_types_values.rs` can be reused for this. Furthermore I assume the `import google/protobuf/...proto` has to be dealt with.

### PR DESCRIPTION
**Pull request by benesch**
Embed the definitions of rustproto.proto and the well-known type protos
in the protobuf-codegen-pure crate. This ensures that the correct
versions of these proto files are available in every installation of
protobuf-codegen-pure. (Previously, users needed to acquire their own
copy of these protos and configure their include paths accordingly.)

Users can still override these embedded definitions by supplying a file
of the correct name, which will be preferred to the embedded
definitions.

Fix #312.

----

@stepancheg not sure if there's an easier or better way to do this. This was the simplest thing I could come up with.

### CODE REVIEW

**Comment by benesch** [comment]
@stepancheg, sorry to bug you, but do you think something like this is mergeable, or should I work around it on my end?

**Comment by stepancheg** [comment]
It is definitely very good PR. Thank you for the ping! I'll look into it closely soon.

File: protobuf-test/build.rs [hunk 1]
```diff
@@ -16,17 +16,15 @@ use protobuf_test_common::build::*;
...
              out_dir,
              input,
-             includes,
              customize,
          }| {
             protoc_rust::Codegen::new()
                 .out_dir(out_dir)
                 .inputs(input)
-                .includes(includes)
+                .includes(&["../proto", include_dir])
```
Comment (stepancheg) [inline protobuf-test/build.rs:27]: Can we make it work without this line? For compatibility with `protoc` which does not require it?

Comment (benesch) [reply protobuf-test/build.rs:27]: So this is actually just inlining a slice that used to live here: https://github.com/stepancheg/rust-protobuf/pull/507/files#diff-d9930b6eababb528edc6d13b26e6d004L223

In other words, protobuf-test has always needed to specify the "../proto" include directory in order to pick up rustproto.proto. (It *is* true that you don't need to specify this if you just want the "google/protobuf" imports, but the protobuf-test photos expect to be able to import "rustproto.proto". I think ideally somehow rustproto.proto would be shipped with `protoc_rust`, but I'm not sure about how to rig that up.)

The change in this PR is to allow protobuf-codegen-pure-test to avoid specifying "../proto", since it's no longer required.

Comment (stepancheg) [reply protobuf-test/build.rs:27]: Ah, it was there before, but specified in common.

I see.

**Comment by stepancheg** [comment]
Thanks again!
